version: '3.3'

services:
  
  # frontend:
  #   image: ${APP}-frontend
  #   container_name: ${APP}-frontend

  # backend:
  #   image: ${APP}-backend
  #   container_name: ${APP}-backend
  #   depends_on:
  #     - database
  #   ports:
  #     - 8080:8080

  database:
    image: postgres
    container_name: ${APP}-pg-db
    restart: always
    environment: 
      - POSTGRES_DB=${PGHOST}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${APP_DB_ADMIN_PASSWORD}
      
    # Bind mount the default Postgres port
    ports:
    - ${PGPORT}:5432

